# Generated by Django 4.0.3 on 2022-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='created',
            field=models.DateField(default='2022-04-29', verbose_name='Erstellt am'),
        ),
    ]
