# Generated by Django 4.0.3 on 2022-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='UserID'),
        ),
    ]
