# Generated by Django 4.0.3 on 2022-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_guest_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='created',
            field=models.DateField(default='2022-05-21', verbose_name='Erstellt am'),
        ),
    ]
