# Generated by Django 4.0.4 on 2022-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_alter_guest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='created',
            field=models.DateField(default='2022-05-26', verbose_name='Erstellt am'),
        ),
    ]
