# Generated by Django 4.0.4 on 2022-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_best_man_userprofile_bride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.TextField(blank=True, null=True, verbose_name='Titelbild'),
        ),
    ]
