# Generated by Django 4.0.3 on 2022-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default='Kein Enddatum', null=True, verbose_name='Fällig am'),
        ),
    ]
