# Generated by Django 4.0.3 on 2022-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['duedate'], 'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='Fällig am'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2022-03-10', verbose_name='Erstellt am'),
        ),
    ]
