# Generated by Django 4.0.3 on 2022-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2022-04-07', verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Notizen'),
        ),
    ]
