# Generated by Django 4.0.3 on 2022-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2022-04-11', verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Offen', 'Offen'), ('In Arbeit', 'In Arbeit'), ('Erledigt', 'Erledigt')], default='Offen', max_length=32, verbose_name='Status'),
        ),
    ]
