# Generated by Django 3.2.5 on 2022-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_created_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_id',
            field=models.IntegerField(default=0, editable=False, verbose_name='UserID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2022-04-27', verbose_name='Erstellt am'),
        ),
    ]
