# Generated by Django 3.2.5 on 2022-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220427_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='UserID'),
        ),
    ]
