# Generated by Django 4.0.4 on 2022-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_options_remove_task_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2022-05-26', verbose_name='Erstellt am'),
        ),
    ]
