# Generated by Django 4.0.3 on 2022-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='UserID'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created',
            field=models.DateField(default='2022-05-06', verbose_name='Erstellt am'),
        ),
    ]
