# Generated by Django 4.0.3 on 2022-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_owner_id_alter_budget_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created',
            field=models.DateField(default='2022-05-21', verbose_name='Erstellt am'),
        ),
    ]
